### ISSUE TITLE
MVC 패턴에 맞도록 디렉토리 구축

### ISSUE THREAD

**Issue by HoSeong0731** [AI-Funding/AI_Funding_BE#7]
Model 
View (FE 레포지토리로 이관)
Control
폴더로 나누고 더 필요한 폴더를 추가할 것
예) 쿼리를 모아두는 Query 폴더
=> ORM을 사용하든 String Builder에 쿼리를 하드코딩하든 해야할 것 같음
예2) API 관련 JSON 토큰 값들 모아두는 폴더
예3) Handler class 들을 모아두는 폴더
=> DB Handler, DataTable Handler 기타 등등 앞으로 개발하면서 많이 사용할 것 같은 Handler들을 모아두는 폴더

**Comment by kwYoohae** [comment]
혹시 GitHub에서 빈 디렉터리를 추가할 수 없는 것으로 알고있습니다.

어떤 특정파일이 존재하지 않으면 `git add`가 안되는 것으로 알고있는데

Github가 아닌 다른곳에서 작성하실 생각이신가요?

**Comment by HoSeong0731** [comment]
해당 디렉토리별 readme가 들어가면 추가되지 않을까 싶습니다 :)

**Comment by HoSeong0731** [comment]
#11 
MVC 패턴으로 디렉토리 세팅 완료했습니다. (2021/1/1일 회의 때)
